[package]
name = "sysmon-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.35.2"
term_cursor = "0.2.1"
ratatui = {version = "0.27.0", features = ["crossterm"]}
crossterm = "0.27.0"
rand = "0.8.5"
